name: 'Publish pruned ical events to gh-pages'
description: 'Prune events by defined days count and publish to csv'
author: 'praecipue'
inputs: 
  ICAL_URL:
    description: 'URL to get .ics file'
    required: true
  DAYS:
    description: 'Define days ago to prune'
    default: '60'
  COMPARE_URL:
    description: 'Push only when file at compared url is diffrent'
    default: ''
runs:
  using: 'composite'
  steps:
    - run: . ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        INPUT_ICAL_URL: ${{ inputs.ICAL_URL }}
        PROCESS_ICAL_PATH: ${{ github.action_path }}/process_ical.py
        INPUT_DAYS: ${{ inputs.DAYS }}
        RUN_NUMBER: ${{ github.run_number }}
        COMPARE_URL: ${{ inputs.COMPARE_URL }}
