name: Prune and push

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: 11,41 6-20 * * *

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  prune:
    runs-on: ubuntu-latest

    steps:
      - name: icalprune
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
        with:
          ICAL_URL: ${{ secrets.ICAL_URL }}
          COMPARE_URL: 'https://praecipue.github.io/icalprune/pruned.tsv'
        uses: praecipue/icalprune@main
        
